### ISSUE TITLE
Pages配下のコンポーネントの名前

### ISSUE THREAD

**Issue by kotu-kotuo** [k-logic563/team-qin-portfolio#8]
Pages配下のコンポーネント名の1文字目は大文字がいいと思います。

**Comment by k-logic563** [comment]
@kotu-kotuo 
すいません、なぜ大文字にしたほうが良いのでしょうか？

**Comment by kotu-kotuo** [comment]
公式のドキュメントでは大文字になっていますし、他の方々のコードも大多数の人が大文字にしているので、そういう慣習があるのではないかと思います。また、小文字にして自分がビルドした時に、vercelでエラーが出たからです。

ドキュメント
https://nextjs.org/docs/basic-features/pages

**Comment by k-logic563** [comment]
@kotu-kotuo 
修正おわりました！ご確認お願いします！

**Comment by kotu-kotuo** [comment]
いいですね！
